alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias tmux='TERM=xterm-256color /usr/bin/tmux'
alias go='~/.scripts/.go'
alias tplate='~/.scripts/.tplate'
alias pf='pdflatex'
alias n='nautilus . &'
alias gno='gnome-open'
alias s='~/.scripts/.ssh_lambda'
alias vpn='ps x | grep openvpn'
alias st='shutdown 0'
alias up='./.update'
